language: python

python:
  - "2.7"

sudo: true

before_install:
  - sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-lxml
  - sudo apt-get install -qq libgeos-dev python-gdal libgdal-dev

install:
#  - pip install -r requirements.txt
  - python setup.py install

script:
#  - find stetl -name "*.py" | xargs flake8
  - cd docs && make html

#after-script:
#  - python todo
