language: python
sudo: true

#env:
#  global:
#   - CPLUS_INCLUDE_PATH=/usr/include/gdal
#   - C_INCLUDE_PATH=/usr/include/gdal

python:
  - "2.7"

addons:
  apt:
    packages:
      - libxslt1-dev
      - libxml2-dev
      - build-essential
      - python-dev
      - python-setuptools
      - libproj0
      - libgeos-dev
      - libgdal-dev
      - libgdal1h
      - gdal-bin
      - python-gdal

#before_install:
  # - sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable GDAL2 conflicts!
#  - sudo apt-get install -qq python-lxml
#  - sudo apt-get install -qq gdal-bin libgeos-dev libproj-dev libgdal-dev

install:
  - pip install -r requirements-dev.txt
  # - python setup.py install

script:
#  - find stetl -name "*.py" | xargs flake8
  - cd docs && make html
  - nose2 -v -c setup.cfg

#after-script:
#  - python todo
