language: python
sudo: true

#env:
#  global:
#   - CPLUS_INCLUDE_PATH=/usr/include/gdal
#   - C_INCLUDE_PATH=/usr/include/gdal

python:
  - "2.7"

before_install:
  - sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update -q
  - sudo apt-get install -qq build-essential python-dev python-setuptools
  - sudo apt-get install -qq libxml2-dev libxslt-dev python-lxml
  - sudo apt-get install -qq libgeos-dev libgdal-dev gdal-bin python-gdal

install:
  - pip install -r requirements-main.txt
  - pip install -r requirements-dev.txt
  - python setup.py install

script:
#  - flake8
  - cd docs && make html
  - nose2 -v -c setup.cfg

#after-script:
#  - python todo
