language: python
sudo: true

env:
  global:
   - CPLUS_INCLUDE_PATH=/usr/include/gdal
   - C_INCLUDE_PATH=/usr/include/gdal

python:
  - "2.7"

#addons:
#  apt:
#    packages:
#      - libproj0
#      - libgeos-dev
#      - libgdal-dev
#      - libgdal1h
#      - libxslt1-dev
#      - libxml2-dev
#      - build-essential
#      - python-dev


before_install:
  # - sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable GDAL2 conflicts!
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential python-dev python-setuptools
  - sudo apt-get install -qq python-lxml
  - sudo apt-get install -qq gdal-bin libgeos-dev libproj-dev libgdal-dev

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  # - python setup.py install

script:
#  - find stetl -name "*.py" | xargs flake8
  - cd docs && make html

#after-script:
#  - python todo
