language: python
sudo: true

env:
  global:
   - CPLUS_INCLUDE_PATH=/usr/include/gdal
   - C_INCLUDE_PATH=/usr/include/gdal

python:
  - "2.7"

before_install:
  - sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update -q
  - sudo apt-get install -qq build-essential python-dev python-setuptools
  - sudo apt-get install -qq python-lxml libgdal-dev python-psycopg2 python-jinja2 gdal-bin

install:
  # follow GDAL installed version for Python bindings
  - pip install GDAL==`gdalinfo --version | cut -d' ' -f2 | cut -d',' -f1`
  # - pip install -r requirements-main.txt
  - python setup.py install
  - pip install -r requirements-dev.txt

script:
#  - flake8
  - cd docs && make html
  - nose2 -v -c setup.cfg
  - cd examples/basics && runall.sh

#after-script:
#  - python todo
